apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolyth-deployment
  labels:
    app: monolyth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolyth
  template:
    metadata:
      labels:
        app: monolyth
    spec:
      containers:
        - name: app
          image: theiqw/go-test-monolith:1.0.0
          ports:
            - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: monolyth-service
spec:
  selector:
    app: monolyth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: monolith-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: monolith
spec:
  hosts:
    - "*"
  gateways:
    - monolith-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: monolyth-service
            port:
              number: 80
